const HTTP_OK = 200;
const HTTP_RESOURCE_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_NOT_FOUND = 404;
const HTTP_RESOURCE_CONFLICT = 409;
const HTTP_SERVER_ERROR = 500;
module.exports={HTTP_OK,HTTP_RESOURCE_CREATED,HTTP_BAD_REQUEST,HTTP_UNAUTHORIZED,HTTP_NOT_FOUND,HTTP_RESOURCE_CONFLICT,HTTP_SERVER_ERROR}